Repository JADSN1894/yew-debugger, pull requests merged in 2023-10, with the labels that each got.

#12 Feat/basic reset events
  README.md
  background.js
  examples/yew-debugger-counter-layout/output.css
  examples/yew-debugger-counter-layout/yew-app/src/components/counter_component.rs
  examples/yew-debugger-counter-layout/yew-app/src/components/mod.rs
  examples/yew-debugger-counter-layout/yew-app/src/lib.rs
  panel/output.css
  panel/wasm/src/lib.rs
  panel/wasm/src/models/mod.rs
  panel/wasm/src/models/theme_mode_model.rs
Labels: enhancement

#13 feat: implement reload application after reset events
  background.js
  docs/yew-debugger-running-with-example.png
  panel/wasm/src/lib.rs
Labels: enhancement

#14 feat: implement model rendering using Rust debug flavor
  Cargo.lock
  Cargo.toml
  examples/yew-debugger-counter-layout/justfile
  examples/yew-debugger-counter-layout/package.json
  examples/yew-debugger-counter-layout/yew-app/Cargo.toml
  examples/yew-debugger-counter-layout/yew-app/src/lib.rs
  panel/wasm/Cargo.toml
  panel/wasm/src/lib.rs
Labels: enhancement

#15 fix: install tooling script
  .devcontainer/install_tooling.sh
Labels: enhancement

#16 docs: update image from readme
  docs/yew-debugger-running-with-example.png
Labels: documentation

#17 feat: Replace justifle for Makefile and bump version of daisyui package
  Makefile
  examples/yew-debugger-counter-layout/Makefile
  examples/yew-debugger-counter-layout/justfile
  examples/yew-debugger-counter-layout/package-lock.json
  examples/yew-debugger-counter-layout/package.json
  panel/package-lock.json
  panel/package.json
  scripts/vscode.sh
Labels: enhancement

#18 feat: artifacts folder
  .gitignore
  Makefile
  examples/yew-debugger-counter-layout/Makefile
  examples/yew-debugger-counter-layout/package-lock.json
  examples/yew-debugger-counter-layout/package.json
  panel/package-lock.json
  panel/package.json
Labels: enhancement

#20 build: refactor directives to implement gh-actions
  .gitignore
  Makefile
  background/Makefile
  examples/yew-debugger-counter-layout/Makefile
  examples/yew-debugger-counter-layout/package-lock.json
  examples/yew-debugger-counter-layout/package.json
  panel/Makefile
  panel/wasm/Makefile
Labels: enhancement

#21 feat: add cargo config for wasm
  .cargo/config.toml
Labels: enhancement

#22 Create makefile.yml
  .github/workflows/makefile.yml
Labels: enhancement

#23 Update README.md
  README.md
Labels: documentation

#26 feat: prepare for publishing
  lib/yew-debugger-derive/Cargo.toml
  lib/yew-debugger/Cargo.toml
Labels: enhancement

#27 Fix/missing fields msg
  .devcontainer/Dockerfile
  Cargo.lock
  background.js
  background/Cargo.toml
  background/src/lib.rs
  examples/yew-debugger-counter-layout/package-lock.json
  examples/yew-debugger-counter-layout/package.json
  panel/output.css
  panel/package.json
  panel/wasm/src/lib.rs
Labels: documentation, enhancement, fix

#28 Fix/scrollbar
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  examples/yew-debugger-counter-layout/index.html
  examples/yew-debugger-counter-layout/package-lock.json
  manifest.json
  panel/index.html
  panel/output.css
  panel/wasm/src/lib.rs
  scripts/vscode.sh
Labels: documentation, enhancement, fix

#29 Docs/getting started
  .github/workflows/makefile.yml
  README.md
  background/src/lib.rs
  devtools.js
  docs/getting-started/01-open-dev-container-in-vscode.png
  docs/getting-started/02-install-vscode-extensions-at-devcontainer.png
  docs/getting-started/03-after-finish-devcontainer.png
  docs/getting-started/04-open-new-terminal.png
  docs/getting-started/05-enable-developer-mode.png
  docs/screenshots/yew-debugger-running-with-example.png
  examples/yew-debugger-counter-layout/index.html
  examples/yew-debugger-counter-layout/package-lock.json
  examples/yew-debugger-counter-layout/yew-app/Cargo.toml
  examples/yew-debugger-counter-layout/yew-app/src/lib.rs
  examples/yew-debugger-counter-layout/yew-app/src/models/counter_model.rs
  examples/yew-debugger-counter-layout/yew-app/src/models/theme_mode_model.rs
  manifest.json
Labels: documentation, enhancement, fix

#30 docs: Update README.md
  README.md
Labels: documentation

#31 fix: better display when EventMetadata msg has arguments
  Cargo.lock
  Cargo.toml
  background.js
  background/src/lib.rs
  content-script.js
  devtools.js
  examples/yew-debugger-counter-layout/package-lock.json
  panel/output.css
  panel/wasm/src/lib.rs
Labels: enhancement, fix

#32 fix: fix width panel right side
  panel/wasm/src/lib.rs
Labels: fix

#35 Update makefile.yml
  .github/workflows/makefile.yml
Labels: enhancement, fix
